### ISSUE TITLE
Black level detection

### ISSUE THREAD

**Issue by simoninns** [simoninns/ld-colourfilter#18]
Right now PalColour only does an 'ok' job of this.  Make the detection more intelligent and resistant to dropouts.

**Comment by simoninns** [comment]
Improved DOC to make black level detection much more reliable

**Comment by techmindorg** [comment]
Be aware that the picture signal, when strong chroma modulation on a dark colour, such as deep blue, can legitimately go quite some way below black in the troughs of the chroma. If you filter out the chroma subcarrier then the average still shouldn't go below black though.
Is it not possible to make the FM demodulator block output a 'magic' value during dropouts, to make them more robust to ignore/work-around?
Or is the issue about dropouts *in* the back-porch causing streaks along the whole line? In which case the work-around should be to do some kind of a median filter, to exclude out-of-the-ballpark values when calculating the black-level. Or even just use one black-level for the whole image, rather than processing it line by line.

**Comment by simoninns** [comment]
The trick was to make the DOC correct the black level detection area of the line in a smarter way, so PALcolour gets a valid measurement - the results are pretty good at the moment in the current app build.  I'd like to make it one value for the frame (as an option), but back-porting the PALcolour code after alteration is very time-consuming, so I'm holding off for the working NTSC/PAL version before merging again.
